server:
  port: 8080
  error:
    include-message: always

spring:
  main:
    web-application-type: servlet
  application:
    name: SpringMasterClass
  datasource:
    url: jdbc:postgresql://localhost:5432/amirgoldb
    username: amirgolmoradi
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  flyway:
    baseline-on-migrate: true
  security:
    user:
      name: admin
      password: admin
